version: '3.5'

services:
  postgres:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 1m
        window: 3m

volumes:
  ais-postgres-vol:
    name: "ais-postgres-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 20
      ebstype: gp2