version: '3.5'

services:
  postgresql:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.01'
          memory: 512M

volumes:
  vessel-postgres-vol:
    name: ${POSTGRES_DATA_VOLUME_NAME:-vessel-postgres-vol}
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 50
      ebstype: gp2