version: '3.5'

services:
  backup-db:
    deploy:
      placement:
        constraints:
          - node.role == worker
          - engine.labels.availability_zone == ${AWS_REGION}${DESIRED_WORKER_AZ}
