version: '3.5'

services:
  postgresql:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          memory: 820M

volumes:
  vessel-postgres-vol:
    name: ${POSTGRES_DATA_VOLUME_NAME:-vessel-postgres-vol}
