version: '3.5'

services:
  postgresql:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          memory: 820M

volumes:
  ais-postgres-vol:
    name: ais-postgres-vol
